name: The Real test
favicon: null
layout_spectrum: 0.1334290171507746
typography_spectrum: 0.8705825917422771
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5030792974866927
  lightness: 0.5378176218364388
  saturation: 0.8757654007058591
  rhythmicContrast: 0.15375302964821458
purpose: []
